permalink: /:title/

title: David Strohmaier
subtitle: Website and Blog
description: >- # this means to ignore newlines until "baseurl:"
  This is the website and blog of David Strohmaier.
author: David Strohmaier
email: david.strohmaier@cl.cam.ac.uk
avatar: assets/images/avatar.jpg

# You'll want to customize url and baseurl for your own site:
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://dstrohmaier.com" # the base hostname & protocol for your site
trueurl: "https://dstrohmaier.com" # needed for rss
blogurl: "" # needed for rss

# Social settings
# Make sure to include the full url including protocol, e.g. https://github.com/chrisbobbe

social:
  linkedin_url: https://www.linkedin.com/in/david-strohmaier-688893109
  github_url: https://github.com/dstrohmaier
  mastodon_url: https://sigmoid.social/@davidstrohmaier
  bluesky_url: https://bsky.app/profile/dstrohmaier.bsky.social

timezone: Europe/London
