permalink: /:title/
plugins:
  - jekyll-sitemap

title: David Strohmaier
subtitle: Website and Blog
description: >- # this means to ignore newlines until "baseurl:"
  This is the website and blog of David Strohmaier.
author: David Strohmaier
email: ds858@cam.ac.uk
avatar: assets/images/avatar.jpg

# You'll want to customize url and baseurl for your own site:
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
trueurl: "http://dstrohmaier.com" #n needed for rss
blogurl: "/blog" # needed for rss

# Social settings
# Make sure to include the full url including protocol, e.g. https://github.com/chrisbobbe
twitter_url:
facebook_url:
googleplus_url:
instagram_url:
linkedin_url: https://www.linkedin.com/in/david-strohmaier-688893109
github_url: https://github.com/dstrohmaier
pinterest_url:
slack_url:
dribbble_url:
